name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure Google Cloud CLI
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v1.1.1
      with:
        project_id: mais-cidade-398922
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: Build and push Docker image
      run: |
        gcloud auth configure-docker
        docker build -t gcr.io/mais-cidade-398922/maiscidade-backend .
        docker push gcr.io/mais-cidade-398922/maiscidade-backend

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy maiscidade-backend \
          --image gcr.io/mais-cidade-398922/maiscidade-backend \
          --platform managed \
          --region=us-central1 \
          --allow-unauthenticated
